package com.mobdeve.gonzales.lee.ong.artemis

enum class Keys {
    KEY_PROFILE_PICTURE,
    KEY_USERNAME,
    KEY_POST,
    KEY_TITLE,
    KEY_NUM_UPVOTES,
    KEY_NUM_COMMENTS,
    KEY_DATE_POSTED,
    KEY_MEDIUM,
    KEY_DIM_HEIGHT,
    KEY_DIM_WIDTH,
    KEY_DESCRIPTION,
    KEY_TAGS,
    KEY_BOOKMARK,
    KEY_UPVOTE,
    KEY_DB_USERS,
    KEY_DB_BIO,
    KEY_DB_USERNAMES,
    KEY_DB_COMMENTS
}